spring:
  application:
    name: back-end
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_authority_system
    username: root
    password: 123456
  # redis
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    # 自定义属性
    expire: 60000
server:
  port: 8080

# jwt 配置
jwt:
  # 密钥
  secret: auth
  # 过期时间(ms)
  expiration: 18000000

# 登录请求地址
request:
  login:
    url: /api/user/login

# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      #全局逻辑删除的实体字段名
      logic-delete-field: isDelete
      #逻辑删除值，默认为1
      logic-delete-value: 1
      #逻辑未删除值，默认为0
      logic-not-delete-value: 0