spring:
  application:
    name: back-end
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/authmanager
    username: root
    password: 123456
server:
  port: 8080

jwt:
  # 密钥
  secret: auth
  # 过期时间(ms)
  expiration: 18000000